<?php
/** @var Popup $block */

use WMZ\QuickAjaxLogin\Block\Popup;

?>

<?php if ($block->isLoggedIn() == false): ?>
    <div class="login-overlay">
        <div class="login-register-popup">
            <div class="response-msg"></div>
            <div class="login-container">
                <form class="popup-login-form" method="POST" data-mage-init='{"validation":{}}'>
                    <div class="container">
                        <label><b><?= /** @noEscape */ __('Email') ?></b></label>
                        <label>
                            <input type="email" name="username" required/>
                        </label>
                        <label><b><?= $block->escapeHtml('Password') ?></b></label>
                        <label>
                            <input type="password" name="password" required
                                   data-validate="{required:true, 'validate-password':true}"/>
                        </label>
                        <button class="action login primary" type="submit">
                            <?= $block->escapeHtml('Login') ?>
                        </button>
                        <div class="register-link">
                            <span><?= $block->escapeHtml('New Here?') ?></span>
                            &nbsp;<a href="#"><?= $block->escapeHtml('Register') ?></a>
                        </div>
                    </div>
                    <div class="container" style="background-color:#f1f1f1">
                        <button title="<?= $block->escapeHtml('Click to close') ?>"
                                type="button" class="cancelbtn">
                            <?= $block->escapeHtml('Cancel') ?>
                        </button>
                        <span class="psw">
                            <a href="<?= /** @noEscape */ $block->getUrl('customer/account/forgotpassword') ?>">
                                <?= $block->escapeHtml('Forgot password') ?>?
                            </a>
                        </span>
                    </div>
                </form>
            </div>
            <div class="register-container">
                <form class="popup-register-form" method="POST" data-mage-init='{"validation":{}}'>
                    <div class="container">
                        <label><b><?= $block->escapeHtml('First Name') ?></b></label>
                        <label><input type="text" name="firstname" required/>
                        </label>
                        <label><b><?= $block->escapeHtml('Last Name') ?></b></label>
                        <label>
                            <input type="text" name="lastname" required/>
                        </label>
                        <label><b><?= $block->escapeHtml('Email') ?></b></label>
                        <label>
                            <input type="email" name="email" required/>
                        </label>
                        <label><b><?= $block->escapeHtml('Password') ?></b></label>
                        <label>
                            <input class="password" type="password" name="password" id="ajaxpassword"
                                   data-validate="{required:true, 'validate-password':true}" required
                                   data-password-min-length
                                   ="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                   data-password-min-character-sets
                                   ="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                            />
                        </label>
                        <label><b><?= $block->escapeHtml('Confirm Password') ?></b></label>
                        <label>
                            <input type="password" name="password_confirmation"
                                   data-validate="{required:true, equalTo:'#ajaxpassword'}" required/>
                        </label>
                        <button class="action login primary"
                                type="submit"><?= $block->escapeHtml('Sign Up') ?>
                        </button>
                        <div class="login-link">
                            <span><?= $block->escapeHtml('Already have an Account?') ?></span>&nbsp;
                            <a href="#"><?= $block->escapeHtml('Login') ?></a>
                        </div>
                    </div>
                    <div class="container" style="background-color:#f1f1f1">
                        <button title="<?= $block->escapeHtml('Click to close') ?>"
                                type="button" class="cancelbtn">
                            Cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        require(['jquery', 'ajaxLogin'], function($, ajaxlogin) {
            ajaxlogin();
        });
    </script>
<?php endif; ?>
